name: Update Rankings

on:
  schedule:
    # 毎日 17:00 ET（＝ 21:00 UTC）に実行
    - cron: '0 21 * * *'
  workflow_dispatch:  # 手動でも実行可能

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install firebase-admin pytz

      - name: Create Firebase credentials file
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" > serviceAccount.json

      - name: Run ranking update script
        run: python .github/scripts/update_rankings.py
